name: All Contributors

on:
  push:
    paths:
      - '.all-contributorsrc'
      - 'README.md'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install All Contributors CLI
        run: npm install -g all-contributors-cli

      - name: Run All Contributors
        run: all-contributors generate

      - name: Commit files
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md .all-contributorsrc
          git commit -m "docs: update contributors [skip ci]" || echo "No changes to commit"
          git push
